package com.pengyu.magnet.domain.match;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.pengyu.magnet.domain.Job;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import java.util.List;

/**
 * Job Requirements generated by AI
 */
@Data
@Entity
@Table(name = "match_job_insights")
@DynamicUpdate
public class JobInsights {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String degree;
    private String major;

    private String experience;
    private String language;

    @OneToOne
    @JoinColumn(name = "job_id",
            referencedColumnName = "id",
            foreignKey = @ForeignKey(name = "job_insights_job_id_fk")
    )
    @JsonIgnore
    private Job job;
    @OneToMany(mappedBy = "jobInsights", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<Skill> skills;
}
