package com.pengyu.magnet.domain.match;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.pengyu.magnet.domain.Job;
import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

/**
 * Job Requirements generated by AI
 */
@Data
@Entity
@Table(name = "match_job_requirement")
public class JobRequirements {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String degree;
    private String major;

    private String experience;
    private String language;

    @OneToOne
    @JoinColumn(name = "job_id",
            referencedColumnName = "id",
            foreignKey = @ForeignKey(name = "job_requirement_job_id_fk")
    )
    @JsonIgnore
    private Job job;
    @OneToMany(mappedBy = "jobRequirements", cascade = CascadeType.ALL)
    private List<Skill> skills;
}
