package com.pengyu.magnet.domain.match;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.pengyu.magnet.domain.Resume;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import java.util.List;

/**
 * Resume Insights generated by AI
 */
@Data
@Entity
@Table(name = "match_resume_insights")
@DynamicUpdate
public class ResumeInsights {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String degree;
    private String major;

    private String experience;
    private String language;

    @OneToOne
    @JoinColumn(name = "resume_id",
            referencedColumnName = "id",
            foreignKey = @ForeignKey(name = "resume_insights_resume_id_fk")
    )
    @JsonIgnore
    private Resume resume;

    @OneToMany(mappedBy = "resumeInsights", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<Skill> skills;

    @Override
    public String toString() {
        return "ResumeInsights{" +
                "id=" + id +
                ", degree='" + degree + '\'' +
                ", major='" + major + '\'' +
                ", experience='" + experience + '\'' +
                ", language='" + language + '\'' +
                ", skills=" + skills +
                '}';
    }
}
